import Head from 'next/head'

import styles from '@/styles/Home.module.scss'
import { FormEvent, useState } from 'react'
import { GetServerSideProps } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { QueryClient, dehydrate, useQuery } from 'react-query'
import $api from '@/lib/http'
import dynamic from 'next/dynamic'
import { useTranslation } from 'next-i18next'
// export async function fetchProduct() {
// 	return (await axios.get('https://jsonplaceholder.typicode.com/todos/1')).data
// }
const SuccessToast = dynamic(() => import('@/components/ui/toast/SuccessToast'))
export default function Home() {
	const [login, setLogin] = useState({
		country_code: '+994',
		code: '',
		phone: '',
	})
	const changeData = (e: FormEvent<HTMLInputElement>) => {
		setLogin({
			...login,
			[e.currentTarget.name]: e.currentTarget.value,
		})
	}
	const userLogin = async (e: FormEvent) => {
		e.preventDefault()
		await $api
			.post('auth/otp/login/confirm', {
				...login,
			})
			.catch(e => console.log(e))
	}

	const [isOpen, setIsOpen] = useState<boolean>(false)
	// const { data, isLoading, isError } = useQuery(
	// 	'product',

	// 	fetchProduct,
	// 	{
	// 		staleTime: Infinity,
	// 		keepPreviousData: true,
	// 		refetchOnWindowFocus: false,
	// 	}
	// )
	// if (isLoading) {
	// 	return <div>Loading...</div>
	// }
	// if (isError) {
	// 	return <div>Smth get wrong</div>
	// }
	const { t } = useTranslation('common')
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<form>
					<input
						type='text'
						name='phone'
						placeholder='phone'
						onChange={changeData}
						value={login.phone}
						className='border py-2 px-3 rounded-md'
					/>
					<input
						type='text'
						name='code'
						onChange={changeData}
						value={login.code}
						placeholder='code'
						className='border py-2 px-3 rounded-md'
					/>
					<button onClick={userLogin}>Send</button>
				</form>

				<p onClick={() => setIsOpen(!isOpen)}>Toggle toast</p>
				<SuccessToast show={isOpen} />
				<div className='h-[200vh]' />
				<p>{t('hello')}</p>
			</main>
		</>
	)
}
export const getServerSideProps: GetServerSideProps = async ctx => {
	// const queryClient = new QueryClient()

	// await queryClient.prefetchQuery(['product'], fetchProduct)
	return {
		props: {
			// dehydratedState: dehydrate(queryClient),
			...(await serverSideTranslations(ctx.locale || 'az', ['common'])),
		},
	}
}
